@accentColor=#5856D6

Component.arc=10

Button.arc=10
Button.margin=4,8,4,8

TextComponent.arc=10
TextField.margin=4,8,4,8
PasswordField.margin=4,8,4,8
ComboBox.padding=4,8,4,8

# Base it on Flat Dark theme
extends=FlatDarkLaf

# Backgrounds
control=#181A20
background=#0B0E11
textBackground=#0B0E11

# Foregrounds
foreground=#EAECEF
textForeground=#EAECEF
selectionForeground=#FFFFFF
selectionBackground=#F0B90B

# Button
button.background=#1E2329
button.foreground=#EAECEF
button.hoverBackground=#2B3139
button.focusedBackground=#2B3139

# Focus/Border
component.borderColor=#2B3139
component.focusColor=#F0B90B

# Scrollbars
scrollBar.thumb=#2B3139
scrollBar.thumbHover=#3A4149

# Highlight
accentColor=#F0B90B

# Table/Grid
table.background=#0B0E11
table.gridColor=#2B3139